apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: kiln-v2
  labels:
    app.kubernetes.io/name: kiln-v2
spec:
  to:
    kind: Service
    name: kiln-v2
  port:
    targetPort: 8080
  tls:
    termination: edge