apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "kiln-v2.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "kiln-v2.fullname" . }}
spec:
  to:
    kind: Service
    name: {{ include "kiln-v2.fullname" . }}
  port:
    targetPort: 8080
  tls:
    termination: edge