apiVersion: v1
kind: Service
metadata:
  name: kiln-v2
  labels:
    app.kubernetes.io/name: kiln-v2
spec:
  selector:
    app.kubernetes.io/name: kiln-v2
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8080