apiVersion: v1
kind: Service
metadata:
  name: {{ include "kiln-v2.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "kiln-v2.fullname" . }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "kiln-v2.fullname" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8080